website/main/routes.py
from flask import Blueprint, redirect, url_for, render_template, request, abort, Flask
from flask import current_app
from website import db
from website.main.forms import SearchForm
from website.main.utils import db_reset, build_destination, make_parks, miles_to_meters, seconds_to_minutes
from website.models import Result
from website.main import gmaps, geolocator
import json, os, requests
import time, asyncio, aiohttp


# create instance of Blueprint; 'main' is the name
main = Blueprint('main', __name__)


# home route
@main.route('/')
@main.route('/home', methods=['GET', 'POST'])
def home():
    form = SearchForm()
    return render_template('home.html', form=form)


# results route
@main.route('/results', methods=['GET', 'POST'])
def results():
    form = SearchForm()
    if form.validate_on_submit():
        DISTANCE_RADIUS = miles_to_meters(form.radius.data)
        city = form.location.data
        location = geolocator.geocode(city)
        longitude = location.longitude
        latitude = location.latitude
        query = ['skatepark', 'skate park']
        skatepark_result = gmaps.places(
            query=query[0] or query[1],
            radius=DISTANCE_RADIUS,
            location=f'{latitude}, {longitude}')['results']
        address_list = [park['formatted_address'] for park in skatepark_result]
        address_string = '|'.join(address_list)
        a = time.time()
        desp = gmaps.distance_matrix(origins=f'{latitude}, {longitude}',
                                     destinations=address_string,
                                     transit_mode='driving')
        names = [park['name'] for park in skatepark_result]
        ratings = [park['rating'] for park in skatepark_result]
        destinations = desp['destination_addresses']
        durations = [
            element['duration'] for element in desp['rows'][0]['elements']
        ]
        distances = [
            element['distance'] for element in desp['rows'][0]['elements']
        ]

        # build up photo_list to be added to Park object
        photo_list = []
        for park in skatepark_result:
            try:
                for photo in park['photos']:
                    reference = photo['photo_reference']
                    photo_url = current_app.config['GPHOTO_URL'] + 'maxheight=' + current_app.config['HEIGHT'] +'&photoreference=' + reference + '&key=' + current_app.config['API_KEY']
                    photo_list.append(photo_url)
            except Exception as e:
                print('ERROR')

        async def fetch(url):
            async with aiohttp.ClientSession() as session:
                async with session.get(url) as response:
                    pass

        # create loop and then run it in another thread
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        tasks = [loop.create_task(fetch(photo_url))]
        loop.run_until_complete(asyncio.wait(tasks))
        loop.close()

        print(city, names, destinations, ratings, durations, distances, photo_list)
        dest_info = build_destination(names, destinations, ratings, distances, durations, photo_list)
        parks = list(make_parks(dest_info))

        # adding to park instance attributes to database
        db_reset()
        for park in parks:
            entry = Result(city=city,
                    name=park.name,
                    address=park.destination,
                    rating=park.rating,
                    distance=park.distance,
                    duration=seconds_to_minutes(park.duration),
                    photo_url=park.photo_url)
            db.session.add(entry)
            db.session.commit()
            
        print(f'speed = {time.time() - a}')    

    # pagination
    page = request.args.get('page', 1, type=int)
    origin = Result.query.with_entities(Result.city).limit(1).scalar()
    print(origin)
    radius = request.form.get('radius')
    page_results = Result.query.paginate(page=page, per_page=2)

    return render_template('results.html', form=form, results=page_results, origin=origin, radius=radius)

website/sort/routes.py
from flask import Blueprint, render_template, request
from website.models import Result


# create instance of Blueprint; 'sort' is the name
sort = Blueprint('sort', __name__)


# highest to lowest rating sort route
@sort.route('/rate_high', methods=['GET', 'POST'])
def rate_high():
    city = Result.query.with_entities(Result.city).limit(1).scalar()
    page = request.args.get('page', 1, type=int)
    page_results = Result.query.order_by(Result.rating.desc())\
                                                .paginate(page=page, per_page=2)
    return render_template('rate_high.html', results=page_results, origin=city)


# lowest to highest rating sort route
@sort.route('/rate_low', methods=['GET', 'POST'])
def rate_low():
    city = Result.query.with_entities(Result.city).limit(1).scalar()
    page = request.args.get('page', 1, type=int)
    page_results = Result.query.order_by(Result.rating.asc())\
                                                .paginate(page=page, per_page=2)
    return render_template('rate_low.html',
                           results=page_results,
                           origin=city)


# fastest to slowest time sort route
@sort.route('/time_fast', methods=['GET', 'POST'])
def time_fast():
    city = Result.query.with_entities(Result.city).limit(1).scalar()
    page = request.args.get('page', 1, type=int)
    page_results = Result.query.order_by(Result.duration.asc())\
                                                .paginate(page=page, per_page=2)
    return render_template('time_fast.html',
                           results=page_results,
                           origin=city)


# slowest to fastest time sort route
@sort.route('/time_slow', methods=['GET', 'POST'])
def time_slow():
    city = Result.query.with_entities(Result.city).limit(1).scalar()
    page = request.args.get('page', 1, type=int)
    page_results = Result.query.order_by(Result.duration.desc())\
                                                .paginate(page=page, per_page=2)
    return render_template('time_slow.html',
                           results=page_results,
                           origin=city)

website/templates/child_layout.html
{% include "layout.html" %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='results.css') }}">
    <div class="bg"></div>
    <div class="bg-img">
        <nav class="navbar-default navbar">
            <a href="{{ url_for('main.home') }}" style="color:rgb(4, 24, 56)">Search</a>
            <select onchange="location = this.value;">
                <option value="">Sort By</option>
                <option value="{{ url_for('sort.rate_high') }}">Rating (High to Low)</option>
                <option value="{{ url_for('sort.rate_low') }}">Rating (Low to High)</option>
                <option value="{{ url_for('sort.time_fast') }}">Time (Fast to Slow)</option>
                <option value="{{ url_for('sort.time_slow') }}">Time (Slow to Fast)</option>
            </select>
        </nav>
    </div>
    </br>
    <header align="center">
        <h1>Parks near {{ origin }}</h1>
    </header>    
    <figure>
        <div class="container">
            <div class="grid">
                {% for park in results.items %}
                <div class="cell">
                    <img src="{{ park['photo_url'] }}" class="responsive-image" width="1000" height="500"/>
                </br>
                        <figcaption align="center">{{ park['name'] }}</figcaption>
                        <figcaption align="center">{{ park['address'] }}</figcaption>
                        <figcaption align="center">Rating: {{ park['rating'] }}</figcaption>
                        <figcaption align="center">Distance: {{ park['distance'] }}</figcaption>
                        <figcaption align="center">Duration: {{ park['duration'] }} minutes away</figcaption>
                </div>
                {% endfor %}
            </div>
        </div>
    </figure>
{% block content %}{% endblock %}

website/templates/home.html
{% extends "layout.html" %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
    <div class="bg"></div>
    <!-- Search form -->
    <div class="bg-img centered">
        <form method="POST" action="{{ url_for('main.results2') }}" class="container-centered">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <div class="form-group">
                        {{ form.location.label(class="form-control-label") }}
                        {% if  form.location.errors %}
                            {{ form.location(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.location.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                        </div>
                    {% else %}
                        {{ form.location(class="form-control form-control-lg") }}
                    {% endif %}
                    </div>
                    <div class="form-group" style="color:white">
                        {{ form.radius.label(class="form-control-label") }}
                        {% if  form.radius.errors %}
                            {{ form.radius(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.radius.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                        </div>
                    {% else %}
                        {{ form.radius(class="form-control form-control-lg") }}
                    {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class='btn btn-outline-info') }}
                </div>
        </form>
    </div>
</body>
{% endblock content %}

website/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Alegreya&display=swap" rel="stylesheet">
    
    {% if title %}
        <title>{{ title }} - Skoogle</title>
    {% else %}
        <title>Skoogle</title>
    {% endif %}
    </head>
    <body>
    {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

website/templates/rate_high.html
{% extends "child_layout.html" %}
{% block content %}
    <nav aria-label="...">
        <ul class="pagination pagination-sm justify-content-center">    
        {% for page_num in results.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if results.page == page_num %}
                    <li class="page-item active"><a class="page-link" href="{{ url_for('sort.rate_high', page=page_num) }}">{{ page_num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="{{ url_for('sort.rate_high', page=page_num) }}">{{ page_num }}</a></li>
                {% endif %}
            {% else %}
                <font color="rgb(4, 24, 56)">...</font>
            {% endif %}
        {% endfor %}
    </nav>
{% endblock content %}

website/templates/rate_low.html
{% extends "child_layout.html" %}
{% block content %}
    <nav aria-label="...">
        <ul class="pagination pagination-sm justify-content-center">    
        {% for page_num in results.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if results.page == page_num %}
                    <li class="page-item active"><a class="page-link" href="{{ url_for('sort.rate_low', page=page_num) }}">{{ page_num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="{{ url_for('sort.rate_low', page=page_num) }}">{{ page_num }}</a></li>
                {% endif %}
            {% else %}
                <font color="rgb(4, 24, 56)">...</font>
            {% endif %}
        {% endfor %}
    </nav>
{% endblock content %}

website/templates/results.html
{% extends "child_layout.html" %}
{% block content %}
    <nav aria-label="...">
        <ul class="pagination pagination-sm justify-content-center">    
        {% for page_num in results.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if results.page == page_num %}
                    <li class="page-item active"><a class="page-link" href="{{ url_for('main.results', page=page_num, radius=radius) }}">{{ page_num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="{{ url_for('main.results', page=page_num, radius=radius) }}">{{ page_num }}</a></li>
                {% endif %}
            {% else %}
                <font color="rgb(4, 24, 56)">...</font>
            {% endif %}
        {% endfor %}
    </nav>
{% endblock content %}

website/templates/time_fast.html
{% extends "child_layout.html" %}
{% block content %}
    <nav aria-label="...">
        <ul class="pagination pagination-sm justify-content-center">    
        {% for page_num in results.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if results.page == page_num %}
                    <li class="page-item active"><a class="page-link" href="{{ url_for('sort.time_fast', page=page_num) }}">{{ page_num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="{{ url_for('sort.time_fast', page=page_num) }}">{{ page_num }}</a></li>
                {% endif %}
            {% else %}
                <font color="rgb(4, 24, 56)">...</font>
            {% endif %}
        {% endfor %}
    </nav>
{% endblock content %}

website/templates/time_slow.html
{% extends "child_layout.html" %}
{% block content %}
    <nav aria-label="...">
        <ul class="pagination pagination-sm justify-content-center">    
        {% for page_num in results.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if results.page == page_num %}
                    <li class="page-item active"><a class="page-link" href="{{ url_for('sort.time_slow', page=page_num) }}">{{ page_num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="{{ url_for('sort.time_slow', page=page_num) }}">{{ page_num }}</a></li>
                {% endif %}
            {% else %}
                <font color="rgb(4, 24, 56)">...</font>
            {% endif %}
        {% endfor %}
    </nav>
{% endblock content %}